//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTClientApplication.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FTDatabaseEntities : DbContext
    {
        public FTDatabaseEntities()
            : base("name=FTDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactInfo> ContactInfo { get; set; }
        public virtual DbSet<Government> Government { get; set; }
        public virtual DbSet<Minister> Minister { get; set; }
        public virtual DbSet<MinisterialPost> MinisterialPost { get; set; }
        public virtual DbSet<Parliament> Parliament { get; set; }
        public virtual DbSet<ParliamentMember> ParliamentMember { get; set; }
        public virtual DbSet<Party> Party { get; set; }
        public virtual DbSet<Politician> Politician { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Constituency> Constituency { get; set; }
        public virtual DbSet<Selection> Selection { get; set; }
        public virtual DbSet<Selection_member> Selection_member { get; set; }
        public virtual DbSet<Mayor> Mayor { get; set; }
        public virtual DbSet<Municipality> Municipality { get; set; }
        public virtual DbSet<Region> Region { get; set; }
    }
}
